# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Preparation'

- script: |
    npm ci
    npm run build:prod
  displayName: 'Build'

- script: |
    npm run test
  displayName: 'Unit Test'

- script: |
    npm run lint
  displayName: 'Static Analysis'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'TESTS-*.xml'

- script: |
    ls -la

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'app'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR Cshion'
    repository: 'spring-petclinic-angular'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build Docker Container'


