# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Preparation'

- script: |
    npm ci
    npm run build:prod
  displayName: 'Build'

- script: |
    npm run test -- --karma-config karma.ci.conf.js
  displayName: 'Unit Tests & IT Tests'

- script: |
    npm run lint
  displayName: 'Static Analysis'

- script: |
    npm run e2e -- --protractor-config protractor.ci.conf.js
  displayName: "E2E Tests"

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'TESTS-*.xml'
    testRunTitle: 'Unit Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/junit'
    failTaskOnFailedTests: true
    testRunTitle: 'E2e Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'app'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR Cshion'
    repository: 'spring-petclinic-angular'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build Docker Container'


